### ISSUE TITLE
Feed list response

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#10]
`/api/feed/` serializes details as:

      "details": {
        "type": 1,
        "id": 26
      }

Please, rename `id` to match serialization of `User` and `Beverage` entities. In this particular case, `id` should be renamed to `pk` in both cases.
Also make sure, that for `type=2` data contains both user's `pk` and user's `name`

**Comment by kostya-p-dev** [comment]
Done 
 "details": {
        "type": 2,
        "pk": 29,
        "name": "Kostya Prosto2"
      }
