### ISSUE TITLE
Redeem Feed entity

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#12]
Couple of notes for preparing Feed entity for Redeem action. Here's the screen of item for a user Vlad Soroka.

<img width="375" alt="screen shot 2017-03-12 at 15 24 16" src="https://cloud.githubusercontent.com/assets/3834896/23832153/1a9054b0-0738-11e7-8007-64f212991418.png">

1. Image should point to Konstantin's profile. (Generally, users shouldn't see their own profile picture in any of these posts)
2. "...Kostya Prosto bought him a drink..." should be "...Kostya Prosto bought _**you**_ a drink..."
3. "You has redeemed...." should be "You **_have_** redeemed"

**Comment by kostya-p-dev** [comment]
Done
