### ISSUE TITLE
Outsider drinks

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#14]
Currently when we request `api/drinks/i_bought/` we receive drinks for outsider users as well. That's the correct behavior. However such drinks with `recipient` field equal to `null` have no information about recipient at all. Which looks like this:

![screen shot 2017-03-14 at 18 03 41](https://cloud.githubusercontent.com/assets/3834896/23909876/96ada620-08e0-11e7-8538-aa7aa0e132e1.png)

We need to be able to display information about receiver that we used during drink creation.
From the top of my head we can include nullable `outsiderReceiverHash` value into response for drink related APIs. In this case client will be responsible for showing receiver name or hash.

Other suggestions are welcomed.

**Comment by kostya-p-dev** [comment]
Done

{
  "data": [
    {
      "pk": 31,
      "outsiderReceiverHash": "33e75ff09dd601bbe69f351039152189",
...

**Comment by volkzayaz** [comment]
Please, substitude whole outsiderReceiverHash concept to storing of raw textual data about recipient. Return raw data to the client as well.

**Comment by kostya-p-dev** [comment]
Done

**Comment by volkzayaz** [comment]
verified in 0.0.9
