### ISSUE TITLE
Outsider requesting drink details

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#15]
User which has drink bought for him just registered in app using his twitter - `volkzayaz_y`. When trying to view details of his drink, server crashed with 500.

`http://104.131.69.192/api/drink/12/`
`Bearer 947fa290a1e995f0aec4bb2d5efd8035`

<img width="832" alt="screen shot 2017-03-14 at 18 16 17" src="https://cloud.githubusercontent.com/assets/3834896/23910412/561fad72-08e2-11e7-854e-e3d031c02aab.png">

**Comment by kostya-p-dev** [comment]
done

**Comment by volkzayaz** [comment]
verified in 0.0.8
