### ISSUE TITLE
data key is invalid

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#16]
Most actions give the following error most of the time.
Examples
- press Link my Twitter account
- choose recipient for drink, then tap on Suggested

It appears to happen on my account for anything that contacts the server, but I am not positive
https://files.slack.com/files-tmb/T04A49W04-F4K1RK43X-f822f0a374/image_uploaded_from_ios_720.jpg

**Comment by volkzayaz** [comment]
@jmatheson Can you post you email or name or twitter handle so we could identify your user in the database?

**Comment by volkzayaz** [comment]
fixed in 0.0.8
