### ISSUE TITLE
Linking twitter does not stick

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#17]
When I press link twitter it asks which of my accounts. I choose one. Then, the UI does not change to indicate that any linking has happened. The text in the app switched to "Unlink Twitter" when you were connected. Same for facebook.

**Comment by volkzayaz** [comment]
@kostya-p-dev Can reproduce for User `id=14`.

Request is:

      POST
      http://104.131.69.192/api/unjoin-social/
      Bearer f564d7c95255acdf6664861655da3e9d
      backend=twitter

Response:

    {
    "data": {
       "pk": 14,
       "name": "Vlad Soroka",
       "email": "volkzayaz@gmail.com",
       " birthday": "06/30/1993",
       "avatarURL": "http://graph.facebook.com/876566762379251/picture?type=large",
       "facebookId": "876566762379251",
       "twitterName": "volkzayaz_y",
       "phoneNumber": null,
       "ballance": 0
      },
       "error": null,
       "code": 200
      }

Note **"twitterName": "volkzayaz_y",** that is not supposed to be there after unlinking user account

**Comment by kostya-p-dev** [comment]
Done
"twitterName": null,  - after unlinking user tw account

**Comment by volkzayaz** [comment]
verified in 0.0.8
