### ISSUE TITLE
My favorite venues

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#18]
My favorite venues does not seem to work. The functionality to add a venue has gone missing from the settings screen.

**Comment by jmatheson** [comment]
Venues don't seem to work at all for me. Maybe that has not been wired up yet.

**Comment by volkzayaz** [comment]
Currently, system adds favorite Venues automatically when you buy someone a drink.

Will add back "Add Venue" screen in the next ios build

**Comment by volkzayaz** [comment]
@jidulberger, @jmatheson. I've got a suggestion regarding this one.
Favorites screen is identical, to one we've got in the "Choose Venue" for under the tab "Favorite".

How about we remove duplicate screen from Settings? 
Instead we'll have two scenarios for adding venue to favorite:
1) Upon buying drink, venue automatically become "favorite".
2) User will swipe on any venue he likes and add it to favorite. This will happen on regular "Choose Venue" screen. The UI will be the following:

https://i.stack.imgur.com/8FDvJ.png

Only the color would be green and caption will be "Add to Favorite". What do you think?

**Comment by jmatheson** [comment]
The main issue with that is we want to encourage users to add their own favorite venues, even if they are not in the process of buying anyone else a drink. There should be a place to maintain (add, remove) from favorites.

**Comment by volkzayaz** [comment]
Got you, @jmatheson. Will work on separate screen.

**Comment by jidulberger** [comment]
In addition, buying a drink for someone else does not entail the user would
want to make it her own favorite. One standard flow will be for User A to
buy User B a drink at User B's favorite place. That should not make User
B's favorite place automatically User A's favorite.

**Comment by volkzayaz** [comment]
@kostya-p-dev, please remove logic for automatically adding Favorite Venue upon buying a Drink as per Josh's comment

**Comment by kostya-p-dev** [comment]
Done

**Comment by volkzayaz** [comment]
verified in 0.0.8
