### ISSUE TITLE
Implement permission switch from OnMe-v1

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#20]
I tapped on permissions in v7 under settings and the app crashed.

**Comment by volkzayaz** [comment]
App used to show the screen with 3 switches:

- Allow location
- Allow location in background
- Allow Contacts

In ios these settings are stored in native iOS Settings Application in the section "OnMe" in the bottom of Settings page. There're no way client code can change those values, we can only request user to switch on or off the actual values in the settings.

I suggest upon clicking on "Permissions row" in OnMe settings redirect user to native Settings App, where he can change actual values for those switches. Will it work @jidulberger, @jmatheson

**Comment by jmatheson** [comment]
What did that button used to do? I don't think it always crashed.

**Comment by volkzayaz** [comment]
The class used to call `PermissionsSettingsViewController`. I think it was meant to sync user's settings across his devices. The problem with such approach is that in ios service permissions are  **Device** specific, not User specific. 

Example: User can have notifications turned on on iphone, but turned off on his ipad. In this case, App can not determine a valid User setting for push notifications. And App can not update those settings. They can only be changed manually via iOS Settings app. Hence I suggest using Settings App as a primary source of settings and eliminate intermediate screen.

**Comment by jmatheson** [comment]
I think that is incorrect. I will see if I can dig up the old code.

**Comment by jmatheson** [comment]
This had nothing to do with separate devices. It was just a deep link to the settings in iOS. There was a nifty way to do this that not a lot of other apps used. It looks like I had it working and checked in code here https://github.com/jmatheson/OnMe/issues/230

**Comment by volkzayaz** [comment]
implemented in 0.0.16

**Comment by jmatheson** [comment]
Most of the things works. Here is what I found that does not work.
1) I never get asked for always on permissions. 
    a) This is a separate ask that we used to have in there I believe when the user went in to view a drink they received for the first time.
    b) I also did not get asked when I flipped allow location in background. Despite Apple having one setting for location it is actually a multiple option and you are allowed to ask separately for each one, so we still have the ability to prompt as we did in the old version.

Near venue with a drink waiting in the push area used to work as follows
- If user had not approved location always on then this switch should be turned off. If the user flips it on we ask here as well (in addition to what was mentioned above).

Push notifications switches used to always be off until the user has approved push notifications. Now it seems to just be on. If one of the ones that are off were switched on then we would ask the user for permission. Once they have given permission we switch them all to on. Then a user can turn them off as they desire.

All the rest of the pop ups and pre questions work great. thank you! really happy with them.

**Comment by volkzayaz** [comment]
1a) Is resolved in the 0.0.19. The conditions for the screen to popup are: Received drink details are opened and User does not have `.authorizedAlways` status for Location.
1b) Switch prompts user for location in case it never asked user before. Otherwise it redirects user to iOS Settings.
2) Made switch dependent on local push notification settings as well.

**Comment by jmatheson** [comment]
I deleted the app
Reinstalled the app
Opened the app logged in and tapped on Allow location while using. got the apple prompt, accepted.
Then tapped allow in background...

I was expecting to get the apple prompt to allow background access, but instead i just dropped into the settings screen. So it does not seem that 1b is working

**Comment by jmatheson** [comment]
1a and 2 both look good. Just 1b that needs work still

**Comment by volkzayaz** [comment]
fixed in 0.0.21

**Comment by jmatheson** [comment]
Woeks
