### ISSUE TITLE
Blank drink received

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#22]
I received a drink from Josh via email. Here is the content I got.

Hi, I just picked up a beverage for you at Mountain Sun Pub & Brewery. Redeem with this link https://onme.link/hu4ToCN

The link redirects without issue to the app, but this is what it looked like when I opened it.
![image](https://cloud.githubusercontent.com/assets/9138265/23989935/7140aa64-0a88-11e7-8f32-5ee9bc5a730e.png)

**Comment by volkzayaz** [comment]
Related to #15

**Comment by kostya-p-dev** [comment]
Done

**Comment by volkzayaz** [comment]
verified in 0.0.8
