### ISSUE TITLE
Add video reposne

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#23]
`/api/video/` returns `Array` with single item of type `Beverge`. Please, modify response to return plain entity `Beverage` without Array wrapper.

**Comment by kostya-p-dev** [comment]
Done.
{
  "data": {
    "pk": 1,
    "drinkId": 1,
     ...
    "user": {
      "pk": 1,
        ...
    }
  },
  "error": null,
  "code": 200
}
