### ISSUE TITLE
Join Auth Credentials

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#24]
Introduce new rule for `/api/join-` methods. Server should reject join operations if there's an existing user with requested credentials. In case user tries adding credential which belongs to other user, server should response with an error. Example response could look like:

    {
       "data" : null,
       "error" : "Service already belong to another user.",
       "code" : 1001
     }

Also, make sure that user is unable to `unjoin` his last authentication server. In case user has only `twitter` linked, he should not be able to `unjoin` it. In case user tries so, server should reject such operation and example response might look like.

    {
       "data" : null,
       "error" : "Illegal operation. Last authentication service can not be unjoined",
       "code" : 1002
     }

**Comment by kostya-p-dev** [comment]
Done

**Comment by volkzayaz** [comment]
verified in 0.0.8
