### ISSUE TITLE
Venue List Response

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#25]
`/api/venues/?favorites=false` returns `Array` of `Venue`s like it should. One `Venue` is serialized as:

    {
      "id": "52c77412498ee9acc1e90889",
      "name": "Liwan Lounge",
      "address": "1783 Westwood Blvd",
      "latitude": 34.050367398772,
      "longitude": -118.43786452205,
      "category": null
    }

`/api/venues/?favorites=true` returns `Array` of `Venue`s like it should as well. However one `Venue` is serialized as:

    {
      "pk": "52c77412498ee9acc1e90889",
      "name": "Liwan Lounge",
      "address": "1783 Westwood Blvd",
      "latitude": 34.050367398772,
      "longitude": -118.43786452205,
      "category": null
    }

Please, unify responses, so they either both return `"pk"` or `"id"`

**Comment by kostya-p-dev** [comment]
Done.
both methods are  returning 'pk'

**Comment by volkzayaz** [comment]
verified in 0.0.8
