### ISSUE TITLE
New Video feed item

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#28]
<img width="377" alt="screen shot 2017-03-19 at 15 00 30" src="https://cloud.githubusercontent.com/assets/3834896/24081088/dc1a0820-0cb4-11e7-851a-eb64720c125f.png">

User +380661413961 opens drink sent by current user. It results in the bottom feed item with:

`+380661413961 opened drink you sent` and image of user +380661413961.

Next, user `+380661413961` sends a video in response. Which results in slightly incorrect feed item. It is the first on the screenshot. The attached image with Egg is the avatar of current user. This picture should have been an avatar of `+380661413961`. Please, update this type of feed to correspond to this logic

**Comment by kostya-p-dev** [comment]
Done

**Comment by volkzayaz** [comment]
verified in 0.0.8
