### ISSUE TITLE
Beverage state transition

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#29]
Currently upon calling `/api/drink/1/`, beverage state is flipped to "viewed" which is correct.
However system generates push and feed item every time `/api/drink/1/` is called. 

System should only generate push and feed item when Beverage has transition in states, i.e. it used to be "New" and now it became "Viewed".

**Comment by kostya-p-dev** [comment]
Done

**Comment by volkzayaz** [comment]
verified in 0.0.8
