### ISSUE TITLE
Beverage details

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#3]
1. `/api/drink/id` does not contain `redeemDate` and `videoList` properties. Please add them.
2. `/api/drinks` shouldn't necessarily contain such vast details about sender/receiver/venue. Names and pictureURL would be sufficient. Not a piority task

**Comment by kostya-p-dev** [comment]
New parameters  -
"videoList": [
      {
        "video": "onme.loc/phpcqDsyf.mp4",
        "thumbnail": "onme.loc/php63ZiEC.mp4"
      },



  "redeemDate": 1486829959, (or null)
