### ISSUE TITLE
Related users

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#30]
http://104.131.69.192/api/related/users/?twitterName=volkzayaz

returns

     {
       "pk": 17,
       "name": "Sam Wilcox",
       .....
       "facebookId": null,
       "twitterName": "volkzayaz_y",
        "phoneNumber": null,
        .....
     }

**"twitterName": "volkzayaz_y",**
System should not return users who are a match only partially

**Comment by kostya-p-dev** [comment]
Done

**Comment by volkzayaz** [comment]
verified in 0.0.9
