### ISSUE TITLE
Log location at time of purchase.

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#31]
We should be logging location if available at time of purchase.
https://github.com/jmatheson/OnMe/issues/328

**Comment by volkzayaz** [comment]
@jmatheson Can you dive in details a bit? From the top of my head:

1) Where should we log location when purchase happens?
2) What should happen if we can't access Location at the moment?
3) What's the reasoning behind logging location?

**Comment by jmatheson** [comment]
1. I believe it used to store in a field on the drink. Log it there or in mixpanel.
2. Don't log a location.
3. We want to understand what circumstances users are in when they buy other people drinks. Do they buy when they are at the bar right now? Are they in the same city? Is it across the world. Couple that with time and we have some rich information which will help us add new features. For example if I buy you a drink at the bar I am at then maybe we should consider adding a feature where the bar can offer me a coupon/discount. Or maybe we learn that drinks are bought to lure friends out to meet them.

**Comment by volkzayaz** [comment]
This definitely sounds like a Mixpanel usecase.

Josh and you wanted to list all Events you're interested in that should be tracked to Mixpanel. Let's add this one to the list.

**Comment by jidulberger** [comment]
Do we have all the tracking from the old app? That would at least be a good start.

**Comment by jmatheson** [comment]
We should, it was all throughout the old codebase.

**Comment by jmatheson** [comment]
@volkzayaz says this is fixed in his comment about #44

**Comment by jmatheson** [comment]
Mixpanel UI shows nothing under any circumstances. Did we rip it out @volkzayaz ? @jidulberger

**Comment by volkzayaz** [comment]
Currently Application does not track anything to Mixpanel. I'm waiting for the list of items, that should be tracked to Mixpanel.

Let me post the list of Trackings I came across during transition:

- Welocme screen
     1. Skip remaining welcome screens
     2. Next welcome screen
     3. Final welcome screen
- Settings screen
     1. Open
     2. Birthday set started
     3. Birthday set completed
     4. Birthday set cancelled
     5. Twitter Linked
     6. Twitter unlinked
     7. View favorites settings
     8. Send Feedback Tapped
     9. Leaving app ( outclick : faq/privacy/facebook/twitter )
     10. Logout
- Sent screen
     1. Open
- Redeem screen
     1. Open
- Beverage Details
     1. Video played
     2. Claim drink
     3. Adding video (drink unclaimed/drink viewed/drink redeemed)
     4. Redeeming drink (at bar/away from bar)
- Premission Settings
     1. Location switched
     2. Contacts switched
     3. Location always switched
- Notification screen
     1. Every switch change
- Choose Venue screen
     1. Venue searching
     2. Venue selected
     3. Venue Category Selected (all/beer/coffee/wine/cocktails)
- Authentication screen
     1. User was interested in other login means
     2. Error facebook
     3. User is new
     4. New signup via FB
     5. User given new user credit
- Favorite venues screen
     1. Adding a favorite
     2. Select venue in favorites
     3. Deleting favorite
- Edit profile screen
     1. Change email
     2. Change name
- Choose recipient screen
     1. Selected recipient from source (contacts/suggested/friends)
- Authentication screen
     1. User was interested in other login means
     2. Error facebook
     3. User is new
     4. New signup via FB
     5. User given new user credit
- Buy screen
     1. Add video/Delete video
     2. Buy using credits (amount)
     3. Payment (amount/recipient/venue/transactionId/metersAwayWhenPurchased)
     4. Choose Venue
     5. Choose Recipient
- General
     1. App opened (normal/from notification)
     2. Notification received
     3. App went to foreground


@jidulberger, @jmatheson, can you look through the list and let me know if any items should be omitted. Or maybe I missed any crucial items. Let me know about them as well

**Comment by jmatheson** [comment]
Great list @volkzayaz , this is actually more comprehensive (by a lot) vs what we had in the old app.

The ones I see that are missing are

Drink list (received and sent)
- user hides/archives row

Balance
- clicked cashout
- if they completed the cashout (how much, the confirmation id, any other relevant info)

Also, I'd like to see inside the venue selection
- what they tapped on (my favs, their favs)
- what tabs they tapped on (ie coffee, beer, etc)
- if and how they used the search area (for venue name and nearby)

Recipient selection
- did they select from bday list, suggeted list, contacts, did they add someone, if so was it via twitter handle, phone number, etc

- if they tapped back out of a screen (particularly useful if they did not complete a task like venue selection)

In general we were logging information like the ID of the recipient and information about the venue across the board when relevant. Particularly the amount. For example we wanted to learn if people chose different dollar amounts depending on the type of venue.

**Comment by jmatheson** [comment]
We also would track things about each user as you can see we had their image, name, sex, what version of the app they were on etc. I think this was set up on load and/or account creation 
![image](https://cloud.githubusercontent.com/assets/9138265/25181677/a0eec614-2555-11e7-9774-2ed65cc04f25.png)

**Comment by volkzayaz** [comment]
All done except for Genereal (Notification Received). 
In ios we can't tell when exactly the notification arrived to device. Our app is given chance to handle notification only if user opened it. There for Events 
`Application opened (from: notification)` would be identical to `Notification Received`.

Fields that are associated with current user are: `email, name, age`. 
Most of the user fields like `City, Country, Timezone, Region..` are automatically picked up by Mixpanel.

@jmatheson, it'd be hard to verify all of the events, as there's so many of them. You might want to keep an eye on the ticket during beta testing. Anyway it's all set up on 0.0.25

**Comment by jmatheson** [comment]
Thanks, will let you know if I see anything missing.
