### ISSUE TITLE
Nearby locations are not nearby

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#32]
Popular venues are super far away and nowhere near my location.
Venues should still be working as described here https://github.com/jmatheson/OnMe/issues/173

Radius should start at 1500 meters, then go to 5000m if not enough venues are returned, then go to 15000 meters if not enough. This ensures we have the most relevant set of results for people in more and less dense areas.

If there are 2 or less venues then it goes to the wider distance.

**Comment by volkzayaz** [comment]
@jmatheson, please verify in 0.0.9 when it's available.

**Comment by jmatheson** [comment]
Seems to be the same as before. All venues are far away. Nothing on any of the tabs show up closer than 2 miles for me (there are a bunch of bars and coffee shops within 1500 meters)

Additionally, when I search for a town nearby it is showing venues 7500 miles away.

**Comment by volkzayaz** [comment]
@kostya-p-dev, please make sure that forsquare request uses `intent=browse` in it's parameters to ensure closest venues are returned first in the list.

**Comment by jmatheson** [comment]
This one is still not working

**Comment by jidulberger** [comment]
This appears to be resolved. I'm closing, but @jmatheson please test as well.
