### ISSUE TITLE
500 Error received when looking at venues

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#33]
![image](https://cloud.githubusercontent.com/assets/9138265/24238416/4d174db6-0ffe-11e7-8e0d-3ca92d0fb7c6.png)

**Comment by volkzayaz** [comment]
caused by #25
Will be fixed in 0.0.9.

**Comment by volkzayaz** [comment]
@jmatheson Please verify and close ticket in ios version 0.0.9

**Comment by jmatheson** [comment]
appears to be working in v10
