### ISSUE TITLE
Venues ratings showing as 0

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#34]
If we do not have a value for ratings or cost/dollars those should show a blank rather than zero and one dollar sign. See old code.

**Comment by volkzayaz** [comment]
caused by #25. Will be fixed in 0.0.9

**Comment by volkzayaz** [comment]
@jmatheson Please verify and close ticket in ios version 0.0.9 when it's ready

**Comment by jmatheson** [comment]
appears to be working
