### ISSUE TITLE
Facebook link should use auth by app

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#36]
Too much friction having to fill out password.

**Comment by volkzayaz** [comment]
As a side note.
http://stackoverflow.com/questions/32635644/default-fbsdkloginbehavior-native-not-working-on-ios-9

Starting from ios9 Facebook removed "Switch to native app" behaviour. 
They now support 2 way of authentication

-   in-app WebBrowser (which we have currently. if user signed in facebook in Safari earlier, app should be able to login him automatically without password)

- System account. If user does not have system account installed, app will fall back to in-app WebBrowser behaviour

**Comment by volkzayaz** [comment]
@jmatheson, please verify in 0.0.10 and close ticket if it is resolved

**Comment by jmatheson** [comment]
We do not need to be backwards compatible to ios9

**Comment by jmatheson** [comment]
![image](https://cloud.githubusercontent.com/assets/9138265/24330223/9e7d426e-1265-11e7-8272-b4fb2f4c11e5.png)

**Comment by jmatheson** [comment]
That image is what I have seen in at least 3-4 apps in iOS 10. 
I agree it was removed in iOS9, but there is a new way now.

**Comment by jmatheson** [comment]
We should also be requesting (but not requiring) friend list and birthday. All the same things we asked for in the old version if we are not doing so already.

**Comment by jmatheson** [comment]
Actually, the login seems to work fine for me in v10, it ran through the exact screen I screenshot above. This is good to be closed once you can confirm it's pulling the friend list and bday (those may require separate issues if we dont already have it)

**Comment by volkzayaz** [comment]
We do request birthday and friend list. These fields will be required when we handle #30
