### ISSUE TITLE
Suggested users

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#38]
Suggested users should be
1) Anyone I have bought or received a drink from
2) Anyone that I am facebook friends with that is also on the app
3) Anyone who is in my contacts list that is on the app (by matching contact email addresses and contact phone numbers)

This was all in the old code.
Note, I had an open ticket to add Twitter followers but I backlogged that ticket, so lets leave that in the backlog.

Birthdays is the same list of people but ordered by birthday (if they have one) instead of alphabetically.

**Comment by kostya-p-dev** [comment]
Done (need to test via fb)

**Comment by volkzayaz** [comment]
Please review: #41, #40

**Comment by volkzayaz** [comment]
verified in 0.0.12

**Comment by volkzayaz** [comment]
@jmatheson, please verify issue in build 0.0.12.

You can use new phone number to register brand new user. Make sure your contacts list contain @jidulberger or my references:

jidulberger@gmail.com,
volkzayaz@gmail.com
+380675777859

**Comment by jmatheson** [comment]
This kind of works, except https://github.com/jmatheson/OnMe-Backend/issues/46 which I have opened separately. 

I need to test where I am connected to someone with a phone number but not facebook. we need to get more users set up
