### ISSUE TITLE
Odd birthday

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#40]
User with `id=24` was registered using facebook. Login token 

`EAAIwhl8ZCgrkBAJ0Q9Kngh4NxwTpOX0ZCKMmJaBndPQvNUzZB7oZAsdE2Y6C30Mpx9Ou6ybF4ZBkzk5rcmwEzqw8wTIdRhPoduf5LpZCWrrlQwDLlIyvPfM0OPlV6Lwi3BwoAjwS7ZBYZACTSeBNPuVJZBU0ClkIm92mTAiNKrtQyq03gBCZAKssyZAoWXQBcrGDcB8ZB5o39nip2ryGRmBUijWhZCYFN1rxbW1QZD`

His "age" field is set to `02/14/1993`. Which is 2 of February 1993.  Rest of the users have "age" in the format `day/month/year`. This user seem to have `month/day/year`. 
As a result on the front end user has empty birthday because there're no 14th month in the calendar.
Please resolve this inconsistency and make all users store birthdate in the same format

Feel free to destroy this user in Database if needed

**Comment by jmatheson** [comment]
In the US they display dates as month/day/year
We should assume US formats for now (some day it'd be great to support the other format)

**Comment by jmatheson** [comment]
of course how it is stored in the back end is less important :)

**Comment by volkzayaz** [comment]
resolved in 0.0.12
