### ISSUE TITLE
Twitter authentication

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#42]
Request:
`/auth/convert-token/`

     { "backend" : "twitter",
        "token" : "3137547063-PWiQuWI8jkTmXk988IlOuUMYZO1op53ArqjQwXK",
        "secret" : "74KPc7lBsMSLcW2K817EBiaT14T99rP2FjlH2tZTRcsku"
      }

Response:
error 500.

**Comment by kostya-p-dev** [comment]
Done
