### ISSUE TITLE
Suggested users

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#43]
User `id=22`. Has over 4 drinks received from User `id=16`. 

Request:
`/api/connected/users/`
`Bearer b16c64bd57e8c5790a28eb199b9efdd7`

Response:

    "data": [
    {
      "pk": 21,
      "name": "+380661413961",
      "email": null,
      "birthday": null,
      "avatarURL": null,
      "facebookId": null,
      "twitterName": null,
      "phoneNumber": "+380661413961",
      "ballance": 0
    }
    ] ,

While user `id=21` should be in the list (he is a contact friend), resulting list should contain User `id=16` as well. He is both **sent drinks** and is a **contact friend**.

**Comment by kostya-p-dev** [comment]
Done
