### ISSUE TITLE
Initial Ballance

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#44]
Upon creating new users add 5 Dollars to their Ballance.

**Comment by kostya-p-dev** [comment]
Done

**Comment by jmatheson** [comment]
In the public release we will need to rework this to work as it did in OnMe-v1.
There will need to be a way for us to change the amount we give people on the fly, track how much we gave each person in a history file.

**Comment by volkzayaz** [comment]
@jmatheson, ballance is already adsigned on the backend so it already could be changed on the fly.
As for tracking, I suggest including it into separate ticket with rest of Mixpanel Analytics requests

**Comment by volkzayaz** [comment]
Use custom logging for purchase, redeem, cashout operation

**Comment by volkzayaz** [comment]
@kostya-p-dev, please introduce new private Table in the DB which will be used as log for all balance change operations.
Table should contain following rows:

`AffectedUser: userId` - user that has change in the balance
`BalanceDelta: Int` - change in the balance during logged operation
`RelatedDrink: drinkId` - drink that user operated upon     
`Date: Date` - date of operation     
`OperationType: String`- could be "buy", "redeem", "cashout".

Logging should be performed upon Drink is bought, Drink is redeemed, Cashout operation is performed.

**Comment by kostya-p-dev** [comment]
Done . table log_balance was created, all mentioned cases will be logged

**Comment by volkzayaz** [comment]
@jmatheson, please verify and close tickets. More deatils on how to test in the qa slack channel.

**Comment by volkzayaz** [comment]
@kostya-p-dev, please update logs to contain new row:
`CurrentBalance: Int`. It should contain user's balance **after** the corresponding operation

**Comment by kostya-p-dev** [comment]
Done
