### ISSUE TITLE
Website/Domain

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#45]
Domain [onmetheapp.com](http://onmetheapp.com) is currently linked with 104.131.69.192.

https://github.com/jmatheson/onmetheapp.com
Please deploy OnMe website by this address.

**Comment by kostya-p-dev** [comment]
Done I deployed website on onmetheapp.com and the API on app.onmetheapp.com

**Comment by jmatheson** [comment]
Some of the items do not seem to be released. For example the images at the top of /faq is missing but was included here https://github.com/jmatheson/onmetheapp.com/tree/master/public/images

**Comment by kostya-p-dev** [comment]
I fixed this problem .

**Comment by jmatheson** [comment]
Works
