### ISSUE TITLE
Suggested list

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#46]
I see myself in the birthday list and the suggested list.
I should not be able to see myself in these lists.

**Comment by volkzayaz** [comment]
Friend table contains records with id=52,53 which are indeed relation between User `id=20` and User `id=20`.

I suspect James might have his own email and phone number in his contact list as a reminder or something. enduro8@gmail.com, +14083983233.

@kostya-p-dev, please make sure we do not make Users friends with themselves.

**Comment by kostya-p-dev** [comment]
Done

**Comment by volkzayaz** [comment]
verified in 0.0.16

**Comment by jmatheson** [comment]
works
