### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#48]
There is no way to delete a favorite venue.
I accidentally added one I do not want.
The last version of the app i could swipe and delete a favorite.

**Comment by volkzayaz** [comment]
Restored feature back. Please, verify in 0.0.13

**Comment by jidulberger** [comment]
I appear to have lost my favorite venues, when trying to add, I'm getting a spinner - opened https://github.com/jmatheson/OnMe-Backend/issues/59
