### ISSUE TITLE
User update

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#5]
Introduce new endpoint for updating user's own properties. Specifically user needs to be able to alter his:

1) birthday
2) name
3) email
4) Top up his balance by given amount

**Comment by kostya-p-dev** [comment]
Done

**Comment by volkzayaz** [comment]
`/api/user-update/` currently returns Array of Users.
Since we can update only current user, please modify response to include single user entity for `data` key of response JSON

**Comment by kostya-p-dev** [comment]
done
