### ISSUE TITLE
Balance is less than $0 (should never be)

### ISSUE THREAD

**Issue by jidulberger** [jmatheson/OnMe-Backend#50]
My current balance in the app is $-9. The balance for a user should never be permitted to drop below $0. 

I believe this may be related to a 500 error where it appears I could not send James a drink and attempted multiple times. After removing the video, I was able to send the drink, but then James appears to have received 3 drinks.

**Comment by jidulberger** [comment]
In case it's not obvious, it's critical that we have a check in place to never allow a sub-0 balance.

**Comment by jmatheson** [comment]
We had quite a bit of double checking in place for this in v1.
It is critical if connection is lost or any other issues arise mid drink purchase that it absolutely does not go through unless we have confirmed payment.

**Comment by volkzayaz** [comment]
@kostya-p-dev, it is indeed possible to perform unlimited drink purchases from the client.

Please, modify `POST /api/drink/`to reject operations if user's balance is smaller than drink amount. Response might look like:

    { "data" : null,
      "code" : 1003,
      "error" : "Insufficient funds"
     }.

**Comment by kostya-p-dev** [comment]
Done

**Comment by volkzayaz** [comment]
Ballance decrement operation is now performed exclusivelly on server in an atomic manner.

Please verify in 0.0.13

**Comment by jidulberger** [comment]
Is there a good way to test this?

**Comment by volkzayaz** [comment]
@jidulberger, try simulating different network conditions using ios Settings->Developer->Network Link Conditioner.

Enable some poor location conditions and test it.
