### ISSUE TITLE
No notifications

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#51]
I am not receiving any iOS notifications.
I have notifications turned on in iOS settings, so it should be working I would think.

**Comment by volkzayaz** [comment]
@jmatheson, I have sent 4 test push notifications to your device. Please let me know if you received them. The content is:

"Test message for James #1"
"Test message for James #2"
"Test message for James #3"
"Test message for James #4"

**Comment by jmatheson** [comment]
Works Now
