### ISSUE TITLE
Notifications in settings not working

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#52]
I tap on Notifications in the OnMe settings screen and nothing happens.
This should bring up a list of what cases I'd like to get notifications.
This used to show a list as of a couple of your releases ago.

**Comment by volkzayaz** [comment]
I will restore this screen. @jmatheson, can you help me clarify requirements?

1) I assume email related switches are no longer relevant and can be ignored, can't they?
2) Keys that were set in Parse's User table are `pushNotifyDrinks`, `pushNotifyBirthday`, `pushFriendJoins`, `pushNearby`. 
Unfortunately I couldn't find any references to these keys in the most recent version of v1 app. Apart from settings these values to the table they were used nowhere in the iOS code. Nor were they used in cloud code.
My guess is that each of the key should block sending out corresponding notification. Can you confirm?

**Comment by volkzayaz** [comment]
please verify in 0.0.16

**Comment by jidulberger** [comment]
I am not getting the location based notification that I am near a venue where a drink is waiting. I tested with Occidental yesterday. This did work in the old version of the app. My location services are enables for always on.

**Comment by volkzayaz** [comment]
@jidulberger, these are unrelated issues. I opened separate ticket for it.
