### ISSUE TITLE
Buying a drink should work with Apple Pay

### ISSUE THREAD

**Issue by jidulberger** [jmatheson/OnMe-Backend#55]

**Comment by volkzayaz** [comment]
Please, use sandbox ApplePay users ad we're currently in a test mode for Apple Pay

**Comment by jidulberger** [comment]
When attempting to use apple pay to buy a drink, I get a spinning wheel and then an error. I'll attach screenshots.
![image_uploaded_from_ios_720-1](https://cloud.githubusercontent.com/assets/2204043/24612696/38dd8728-1843-11e7-94ff-1e3aa188e63a.jpg)
![image_uploaded_from_ios_720](https://cloud.githubusercontent.com/assets/2204043/24612702/3c792090-1843-11e7-93c8-d489ca8827dc.jpg)

**Comment by volkzayaz** [comment]
Used to have merchant certificate disabled on developer.apple.com. After enabling it received following error from Apple Pay:

     Error Domain=com.stripe.lib Code=50 "The certificate used to sign your request is invalid. 
     For help troubleshooting, please visit https://stripe.com/docs/apple-pay/apps#troubleshooting." 
     UserInfo={com.stripe.lib:ErrorMessageKey=The certificate used to sign your request is invalid. 
     For help troubleshooting, please visit https://stripe.com/docs/apple-pay/apps#troubleshooting., 
     NSLocalizedDescription=The certificate used to sign your request is invalid. For help troubleshooting, please visit https://stripe.com/docs/apple-pay/apps#troubleshooting.}

Seems like Stripe has improper private key + certificate stored. @jmatheson, @jidulberger can you give me Read&Write Access to Stripe dashboard so I could do it?

**Comment by volkzayaz** [comment]
Updated certificates. Should work with sandbox users. @jidulberger, please verify when appropriate
