### ISSUE TITLE
Venue list quality is poor

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#56]
Can you confirm if we are using Intent=browse in the newest foursquare code you are using? the quality of the venue selection is not good. We spent quite a bit of time in OnMe-v1 getting the list to be useful. First guess is that we might be missing intent=browse in the current version

https://github.com/jmatheson/OnMe/blob/032ace56bfaf5f80477eb575807ef267f4f11b5b/OnMe/NearbyVenuesViewController.swift#L949

**Comment by volkzayaz** [comment]
Dependent on #32, #35.

**Comment by volkzayaz** [comment]
Closing issue because dependent tickets have been closed
