### ISSUE TITLE
Upload Video

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#57]
`api/video/` endpoint always returns 500. For example for beverage `id=51`.

Parameters that are sent from the client:

drinkId=51
video=file.mp4
thumbnail=file.jpg  
shouldNotify="true"

**Comment by kostya-p-dev** [comment]
Done

**Comment by volkzayaz** [comment]
Issue can still be reproduced on drink `id=37`. 
However video is added to the list upon consequent details request

**Comment by kostya-p-dev** [comment]
fixed

**Comment by volkzayaz** [comment]
Resolved in 0.0.13.
