### ISSUE TITLE
Request Favorite list

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#58]
I misunderstood Favorite venues request. #54 explains feature. 

Please, implement new API for requesting favorite Venues of arbitrary User. I suggest splitting this API from `GET /api/venues/`. Let's remove `favorites: Boolean` parameter from it completely. Instead let's introduce new endpoint like `GET /api/venues/favorite/` which has absolutely same response structure. But has input parameter like `userId=12`

**Comment by kostya-p-dev** [comment]
Done . I created new API method /api/venues/favorite/

**Comment by volkzayaz** [comment]
implemented in 0.0.14
