### ISSUE TITLE
Authentication responses

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#6]
`/api/join-`
`/api/unjoin-`

endpoints should return updated current user

**Comment by kostya-p-dev** [comment]
done

**Comment by volkzayaz** [comment]
In case user joins phone with incorrect number, API returns:

     {
        "data": [],
        "error": "Invalid code. Please try again.",
         "code": 200
     }

please, make `data` key contain `null` value instead of empty Array

**Comment by volkzayaz** [comment]
For all `unjoin` methods, please make `data` key contain single entity of `User` instead of Array of single `User`

**Comment by kostya-p-dev** [comment]
Done
