### ISSUE TITLE
Notification Settings API

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#60]
As per #52.

Each user should have an ability to disable/enable some push notifications at will. 
Notification settings could be updated and retrieved from server.

There're 4 type of notifications to store:
1) Drink related ( buy/receive, view, redeem, video )
2) User birthday
3) Friend joined 
4) Near Venue (this one is fully managed on client)

First part of the task is to implement 2 API methods for storing and retrieving settings. For example:

     GET /api/push-settings/   
     POST /api/push-settings/

 
Settings serialization might look like: 

     { 
       "drink" : boolean,
       "birthday" : boolean,
       "friendJoined" : boolean,
       "nearVenue" : boolean
     }
                      
By default all push notification types are enabled and should be set to `true`

Second task - update push sending logic to take into account User's settings. For server these are pushes of types 1,2,3. `Near Venue` push type will be managed on the client

**Comment by kostya-p-dev** [comment]
Resolved

**Comment by volkzayaz** [comment]
verified in 0.0.16
