### ISSUE TITLE
Gift drink not showing in Redeem tab, despite notification that drink was received

### ISSUE THREAD

**Issue by jidulberger** [jmatheson/OnMe-Backend#62]
I have a notification that Jim bought be a drink at starbucks. The drink does not show up in Redeem, but I can click on the drink from the Activity Feed (it opens the Gift Detail and allows me to redeem it).

At no point does this drink appear in Redeem (see screenshots).

**Comment by jidulberger** [comment]
![img_6884](https://cloud.githubusercontent.com/assets/2204043/24664942/2517c858-1919-11e7-9f49-a88b277f46df.PNG)
![img_6885](https://cloud.githubusercontent.com/assets/2204043/24664943/251a6c0c-1919-11e7-930f-2b8bd0bc7536.PNG)
![img_6886](https://cloud.githubusercontent.com/assets/2204043/24664944/251a9eac-1919-11e7-9d4e-e60ca6f6ea44.PNG)

**Comment by volkzayaz** [comment]
Currently application does not refresh list automatically upon receiving a drink unless app is restarted. 
App will now refresh list upon receiving push notification about new beverages.

Alternatively you can use pull-to-refresh.

please verify in 0.0.15
