### ISSUE TITLE
When using stripe (test), accounting is poor - adding gift amount to balance, then stating there is enough credit

### ISSUE THREAD

**Issue by jidulberger** [jmatheson/OnMe-Backend#63]
![img_6888](https://cloud.githubusercontent.com/assets/2204043/24666553/ea158092-191d-11e7-91e5-90d017345b3f.PNG)
![img_6889](https://cloud.githubusercontent.com/assets/2204043/24666565/f134f8bc-191d-11e7-9900-c1d763333145.PNG)
![img_6890](https://cloud.githubusercontent.com/assets/2204043/24666568/f419a474-191d-11e7-8d50-2c0e9e428a36.PNG)

**Comment by volkzayaz** [comment]
Removed presenting credit sheet upon paying with PaymentProvider. 
Updated charge rules to charge only for (price - balance) rather than price.

@jidulberger, please verify in 0.0.15
