### ISSUE TITLE
Video camera icon should indicate an attached video

### ISSUE THREAD

**Issue by jidulberger** [jmatheson/OnMe-Backend#69]
![img_6892](https://cloud.githubusercontent.com/assets/2204043/24765046/9a6afc2e-1ab3-11e7-970e-3b61488f575d.PNG)
![img_6893](https://cloud.githubusercontent.com/assets/2204043/24765047/9a6e059a-1ab3-11e7-8756-0b2d32fd5e7c.PNG)

In both the Sent and Redeem tab, video camera icon should be used to indicate a video. Attached is an example of the video camera indicator with no video attached to the gift.

**Comment by volkzayaz** [comment]
@kostya-p-dev, currently `/api/drinks/` returns beverages that do not contain associated videos.
Please either add videos to response serialization or introduce new field `hasVideos: Bool` if including videos in response is a heavy operation. Fisrt one is preferable

**Comment by kostya-p-dev** [comment]
Done. I added videos to response serialization of /api/drinks/

**Comment by volkzayaz** [comment]
Fixed cell to contain Camera icon only if there's a video attached. @jidulberger, please verify in 0.0.18 and close ticket

**Comment by jmatheson** [comment]
Same goes for the Can't hear message below the image. That message does not belong there unless a video is attached.

**Comment by volkzayaz** [comment]
fixed in 0.0.19. Please verify

**Comment by jmatheson** [comment]
looks fixed to me @jidulberger
