### ISSUE TITLE
User should receive warning when attempting to redeem a drink that is at not-nearby venue

### ISSUE THREAD

**Issue by jidulberger** [jmatheson/OnMe-Backend#70]
We also used to warn the user when she was attempting to redeem a drink at a location she was not close to. 

The warning should be in a modal that says "[Venue] is [xxx] miles away, are you sure you want to redeem this gift?" - the user should have a choice to cancel, in which case the gift remains unredeemed. The user can also choose to proceed.

**Comment by volkzayaz** [comment]
The check was in place. Confused signs and app currently warns you if you are really close to the venue. Fixed in the 0.0.19. @jidulberger, bought you a drink in my hometown. Please verify.

**Comment by jmatheson** [comment]
@jidulberger  posted in slack that this is fixed
