### ISSUE TITLE
Badge Homescreen Icon

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#71]
Badge does not appear on home icon when message received.
It seems to appear but only after I open the app instead of right away.
See screenshots (in order).

**Comment by jmatheson** [comment]
![image](https://cloud.githubusercontent.com/assets/9138265/24843704/adbc31ca-1de8-11e7-80dd-237af2761d8d.png)

**Comment by jmatheson** [comment]
![image](https://cloud.githubusercontent.com/assets/9138265/24843711/b74c562a-1de8-11e7-95e1-339d590d34b0.png)

**Comment by jmatheson** [comment]
![img_7685](https://cloud.githubusercontent.com/assets/9138265/24843735/df8815c0-1de8-11e7-9941-6c4c9e471407.jpg)

**Comment by jmatheson** [comment]
![img_7686](https://cloud.githubusercontent.com/assets/9138265/24843743/f3ffafea-1de8-11e7-96ae-8165de1cd65d.png)

**Comment by jmatheson** [comment]
![img_7687](https://cloud.githubusercontent.com/assets/9138265/24843749/0241ebfe-1de9-11e7-85d0-e14b67d18e59.png)

**Comment by jmatheson** [comment]
Last image you can see there is no badge. Now I open the app. Then close it then see badge in final screenshot.

![img_7688](https://cloud.githubusercontent.com/assets/9138265/24843762/20b4985c-1de9-11e7-9bb4-5b921e7c10e7.png)

**Comment by jmatheson** [comment]
![img_7689](https://cloud.githubusercontent.com/assets/9138265/24843765/2e21e0ee-1de9-11e7-8653-7886d391ca99.png)

**Comment by volkzayaz** [comment]
Fixed in the existing 0.0.18. @jmatheson, please verify.

**Comment by jmatheson** [comment]
Works
