### ISSUE TITLE
Cashout should result in user withdrawing funds from app - currently does not work

### ISSUE THREAD

**Issue by jidulberger** [jmatheson/OnMe-Backend#72]
In Settings, clicking "cashout" does nothing.

Clicking cashout should result in the user's balance being transferred to the user. This can be through stripe or paypal.

**Comment by volkzayaz** [comment]
After I inspected Stripe transfers API and chat with you about pros and cons of it I received the following message from @jmatheson.

----- March 30th -----
james [12:20 PM] 
Let me chat with Josh about this offline and figure out what makes the most sense to do.

I never got updated on the issue. Can you elaborate more on your decision?

**Comment by jmatheson** [comment]
Jim to double check paypal is an option and then get back to vlad

**Comment by jmatheson** [comment]
Let's discuss on our next call.

Notes:
In the past we worked with paypay via Braintree.
Braintree is telling me that we need to upgrade to the newer API here https://github.com/paypal/TLS-update/tree/master/Braintree

I have invited Vlad to this account. He can share his account with K as needed.

Our previous version of the app was integrated with Braintree that allowed users to pay via paypal or venmo integration. It was pretty easy and slick to set up. 

We may want to do this if we are in here working on cashout. In general I like the idea of having both vendors if we need to make a switch in the future.

**Comment by jmatheson** [comment]
@jidulberger check out the detached credits portion of this page https://articles.braintreepayments.com/control-panel/transactions/refunds-voids-credits

**Comment by jmatheson** [comment]
Vlad to implement solution where user gives their email address for paypal. Vlad to post solution design here.

**Comment by volkzayaz** [comment]
Here's how I see it. The transactions are sensitive operations, so it's better to offload as much work as possible to be automatic. To make sure that admin accidentally not corrupt data.

Let's build a web page with admin only access. The web page is a list of requested cashouts by users. Each row in the list contains 

- Requested User data. (Name, ballance, paypal email...)
- Requested transfer amount NET. 
- Button to mark transfer complete. 
- Button to mark transfer error with obligatory comment section.

Whenever user requests cashout iOS app will post new transaction to this table. Once a day server will send email to josh@onmetheapp.com and james@onmetheapp.com with reminder to look into table. Optionally email can contain new latest transactions.

Admin will manually transfer funds to based on the transaction details. If transaction is marked successful User receives a notification and feed entry with "OnMe sent you x$.".  Afterwards transaction is no longer appears on the list.
If transaction is marked unsuccessful, push with feed entry is sent with description provided by admin. Transaction is no longer available as well. User has to perform another cashout operation.

Makes sence? @jmatheson, @jidulberger

**Comment by jmatheson** [comment]
Sounds good @volkzayaz

**Comment by jidulberger** [comment]
I agree, this will work. I think it will be nice if the admin email reminder goes out only when there are open transactions, otherwise it may be too easy to ignore.
