### ISSUE TITLE
International phone number verification

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#75]
I noticed you had an international number set for yourself previously vlad. Can we support this on the front end?

**Comment by volkzayaz** [comment]
I removed auto "+1" adding. The rules are the following:
1) App uses default locale to try to format the phone number you input. So if you have your region set to US, app will convert input 7183431415 into (718)-343-1415. This applies to any other region as well.
2) If you'd like to use international number (other region then yours) you must start typing with "+" sign.

Try new logic in 0.0.22 and let me know if UX is acceptable.

**Comment by jmatheson** [comment]
Does not work. I can not type in anything to the phone number box. It does not work

**Comment by volkzayaz** [comment]
accidentally set view to be hidden.
Fixed in 0.0.23

**Comment by jmatheson** [comment]
Works

**Comment by jmatheson** [comment]
Before we close though, @jidulberger this is what the UI looks like.
I have to add +61 and then my phone number. It works fine, but not super intuitive since the default displays an example US number. Any ideas on how we can make it more visibly clear?

![image](https://cloud.githubusercontent.com/assets/9138265/25180304/cf52df5e-2550-11e7-91f6-306cb06d2734.png)

**Comment by jidulberger** [comment]
We could add a field for country (defaults to US) and allows a user to select the country. 

Something like this might be useful for the lookup between country and country_code:
https://github.com/rmaddy/RMPhoneFormat

**Comment by jidulberger** [comment]
It sounds like this is a result of the region settings on the phone. However, let's format the example number based on the local region of the user's phone.

**Comment by volkzayaz** [comment]
resolved in 0.0.24

**Comment by jmatheson** [comment]
works
