### ISSUE TITLE
Badge issue

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#77]
Got a drink and video from josh. Home badge worked. But later it still said two despite the bell showing zero. Then i tapped on bell and the two were unread. Then it went to -2 on the bell and home screen went to zero

**Comment by volkzayaz** [comment]
It was a race condition when app tried to decrease "viewed" counter and update unread counter from server at the same time. I resolved issue by making these operations atomic. Try in 0.0.20

**Comment by jmatheson** [comment]
I assume this is fixed now
