### ISSUE TITLE
Beverage details serialization

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#85]
`/api/drink/132/` returns poorly serialized Venue object

    "venue": {
      "id": "51092ad9e4b0ea82e14f9880",
      "venueId": "51092ad9e4b0ea82e14f9880",
      "price": 2,
      "rating": 8.9,
      "name": "Бар Mokka",
      "address": "вул. Бакулiна, 3",
      "latitude": 50.015710778849,
      "longitude": 36.223783128319,
      "category": 2
    }

Note duplicated `id` keys. Also all `Venue` objects returned from server have `pk` key for their identifier. Please unify Venue serialization.

**Comment by kostya-p-dev** [comment]
done

**Comment by volkzayaz** [comment]
server returns internal venue ID that is unusable for making requests and referencing this venue.

Please reconsider solution to return Foursquare Venue Id in the given "pk" key
