### ISSUE TITLE
Forsquare query

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#86]
@kostya-p-dev, please update rules for searching through Venues via foursquare. Each of the categories, that is passed to you by client, should include each of the corresponding Foursquare categories from the following table:

[VenueCategories.json.zip](https://github.com/jmatheson/OnMe-Backend/files/923474/VenueCategories.json.zip)

Category "All" must include all of the categories from the table.

**Comment by kostya-p-dev** [comment]
Done
