### ISSUE TITLE
No indication for status of sent drinks

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#87]
Sent drinks should have status flags (new, redeemed etc)  just like received. The logic is slightly different. Be sure to check how it used to work.

**Comment by volkzayaz** [comment]
Restored behaviour. @jmatheson, please verify in 0.0.23

**Comment by jmatheson** [comment]
Unable to fully test until this is fixed
https://github.com/jmatheson/OnMe-Backend/issues/88

**Comment by jmatheson** [comment]
works
