### ISSUE TITLE
Error when buying a drink

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#88]
![image](https://cloud.githubusercontent.com/assets/9138265/25154864/bf896780-24d5-11e7-889d-6ca231a860c8.png)

**Comment by jmatheson** [comment]
It is working now, but was there was something fixed @volkzayaz ?
If not, can you explain the issue so we can understand it

**Comment by volkzayaz** [comment]
@kostya-p-dev, please unify responses for serialization of `Venue` entity across the application. 

     1) /api/venues/
     2) /api/venues/favorite?userId=4
     3) /api/drink/132

The following endpoints should return identically serialized entities. Currently there's inconsistency in `"id/pk/venueId"` keys. 1) returns

      {
         "pk": "4161e400f964a520641d1fe3",
         "name": "Urth Caffé",
         "address": "8565 Melrose Ave",
         "latitude": 34.082074026273,
         "longitude": -118.3788710305,
         "category": null
      },

2) returns 
   
    {
      "pk": 4,
      "id": "57582e0f498e3c5c6e23d360",
      "venueId": "57582e0f498e3c5c6e23d360",
      "price": "2",
      "rating": "8.1",
      "name": "Benedict Daily Bar",
      "address": "вул. Сумська, 80",
      "latitude": "50.006518539413",
      "longitude": "36.236987113953",
      "category": null
    },

3) returns

{
      "pk": "57582e0f498e3c5c6e23d360",
      "id": "57582e0f498e3c5c6e23d360",
      "venueId": "57582e0f498e3c5c6e23d360",
      "price": "2",
      "rating": "8.1",
      "name": "Benedict Daily Bar",
      "address": "вул. Сумська, 80",
      "latitude": "50.006518539413",
      "longitude": "36.236987113953",
      "category": null
    },

**Comment by kostya-p-dev** [comment]
Done. 
I updated responses from  
 1) /api/venues/
 2) /api/venues/favorite?userId=4
 3) /api/drink/132
in all responses client will get "pk": "57582e0f498e3c5c6e23d360".
