### ISSUE TITLE
Beverage Viewed state

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#9]
Currently there's no way for a beverage to become "viewed".

We can either:
1) Upon client calling `api/drink/id` and if current user is the drink's receiver, server would set drink's state as "viewed".
2) Introduce new API for marking beverage as "viewed". Than the client would be responsible for calling it when appropriate

**Comment by kostya-p-dev** [comment]
Done . case 1.Upon client calling api/drink/id

**Comment by volkzayaz** [comment]
Current implementation changes state to `viewed` even if drink was previously redeemed. In case drink is redeemed, it's state should not be changed to `viewed`. 

The transition to `viewed` state should happen only if drink was `new` and only if `receiver` requests it.

**Comment by volkzayaz** [comment]
As a result it's possible to redeem the same drink multiple times. It's a serious violation since it allows user to receive unlimited money credits to his account which could be extremely harmful for Product Owner. Please disallow redeeming the same drink multiple times on server side as well.

**Comment by kostya-p-dev** [comment]
done

**Comment by volkzayaz** [comment]
verified in 0.0.8
