### ISSUE TITLE
Cash out flow

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#90]
@kostya-p-dev, introduce endpoints for cash out flow described in ticket #72.

1) 2 API needed.
   a) Create cash out request. Users will create it when decide to cash out funds from OnMe.
     Parameters:
         `email:String /// can be different from users's email`
         `amount: Int /// number of dollars to be deducted from balance`
      Note, upon submitting request user's `ballance` is IMMEDIATELY, credited for requested amount.
    b) Get OnMe fee percent. OnMe will charge small fee from each cashout. It should be variable.
        Responce:
           `fee: Double /// normalized value. If fee is set to 23.5% endpoint returns 0.235`
2) Admin dashboard. Features needed:
     a) list with active cash out requests. These requests are created by users and processed by admin.
        Each request should contain:

           - username: String, 
           - email: String/// email from transfer request
           - amount: Int ////Gross value that was deducted from user
           - OnMe fee: Double///Amount multiplied by fee variable from API
           - debit: Double/// Net value that should be transfered to user by admin. Equals to Gross value minus fee
           - success button/// Request is removed from admin list. User is sent push + feed item described in part 3 of the ticket
           - error button with MANDATORY NOT NULL text field with description. Description is filled by admin/// Request is removed from admin list. User is sent push + feed item described in part 3. User gets Gross amount debited to his balance.

3) New push notification + feed item. Structure should be identical to one described in #10, #12. 

       "details": {
           "type": 3, ///new type for transfer status. It could be 1 for beverage, 2 for user
       }

    for feed item use the following description for keys:

         "pictureURL": OnMe icon URL,
         "text": "OnMe successfully transfered you X$" /// For successful transactions, X is NET amount after fee deduction
                  Admin provided description /////For unsuccessful transaction.

4) Once a day if there are new requests email reminder should be sent to james@onmetheapp.com and josh@onmetheapp.com. Do not send emails if there are no new requests.

**Comment by kostya-p-dev** [comment]
Done . I didn't find email template for cash out . So i created new one .

**Comment by kostya-p-dev** [comment]
admin panel - http://app.onmetheapp.com/admin/

**Comment by jmatheson** [comment]
Must have at least $10 in account to cash out. This configurable if we want to change it.

**Comment by volkzayaz** [comment]
@kostya-p-dev, please provide UI on admin panel to change `fee: Double` percentage.
Updated percent should have **NO** impact on existing unprocessed transactions

**Comment by kostya-p-dev** [comment]
I created Settings section in admin panel to config onme fee and minimal user balance ($10) http://i.prntscr.com/d4350bc63223436e8f66b1cdcc8868f9.png

**Comment by volkzayaz** [comment]
verified
