### ISSUE TITLE
Cash out updated ballance

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#92]
User has 849 USD on his balance. He submits request to cash out 10$. The result is correct:

![screen shot 2017-05-31 at 13 23 34](https://cloud.githubusercontent.com/assets/3834896/26627871/a04e83fa-4604-11e7-8448-cc06b4c4d8f5.png)

Now he requests new cash out for 20$. The updated ballance row for first request changed from 839 to 819.

![screen shot 2017-05-31 at 13 23 56](https://cloud.githubusercontent.com/assets/3834896/26627894/b6cf206c-4604-11e7-8d2e-83babc2f185b.png)

Please, make sure that updated balance field is independent from separate cash out requests

**Comment by kostya-p-dev** [comment]
Done

**Comment by volkzayaz** [comment]
verified
