### ISSUE TITLE
Dev Environment

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#94]
@kostya-p-dev, as we're rolling out app for beta testers we need separate environment for Development and Internal Testing.

Please introduce one new environment for both of these activities. Let current environment and configurations be PRODUCTION. So all of the beta testers will be using `app.onmetheapp.com/api` endpoint and corresponding database.

Upon competition post environment base URL and any other environment specific configs in this ticket.

**Comment by kostya-p-dev** [comment]
done http://104.131.69.192:8080/
