### ISSUE TITLE
Enhance Buying notification interfaces

### ISSUE THREAD

**Issue by volkzayaz** [jmatheson/OnMe-Backend#97]
Current API for drink buying with and without video became flooded with state flags.

1. `POST /api/drink/    hasVideo=true` (if true. email wont be sent)
2. `POST /api/video/  shouldNotify=true`,  isNewDrink=true (optional for emailing), isNewDrinkClaim=true (optional)

The reason behind is complex notification mechanism including pushes, feed items and emails. Let's simplify interfaces for interaction.

@kostya-p-dev, I suggest the following:

1. `POST /api/drinks`   should become form-data method with new optional parameters:

```
video=file.mp4
thumbnail=file.jpg  
```
`hasVideo=true` in this case will make no sense and will just go away.

2. `POST /api/claim_drink/` will have new optional parameters as well similar to `/api/drinks` for adding video file.

3. `POST /api/video/` will be now used exclusively for adding **new** videos. Hence all of the existing flags `shouldNotify, isNewDrink, isNewDrinkClaim` will become obsolete. They are always equal to `true` now and can be removed from interface.

Please comment if I missed anything or made wrong conclusions regarding API usage.

**Comment by kostya-p-dev** [comment]
Done . parameters  hasVideo, shouldNotify, isNewDrink, isNewDrinkClaim are deprecated

**Comment by volkzayaz** [comment]
verified in 2.0.4
